/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScannerRouteImport } from './routes/scanner'
import { Route as RuLiveRouteImport } from './routes/ru-live'
import { Route as QuickRouteImport } from './routes/quick'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as OddsRouteImport } from './routes/odds'
import { Route as LiveRouteImport } from './routes/live'
import { Route as BookmakersRouteImport } from './routes/bookmakers'
import { Route as IndexRouteImport } from './routes/index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const RuLiveRoute = RuLiveRouteImport.update({
  id: '/ru-live',
  path: '/ru-live',
  getParentRoute: () => rootRouteImport,
} as any)
const QuickRoute = QuickRouteImport.update({
  id: '/quick',
  path: '/quick',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const OddsRoute = OddsRouteImport.update({
  id: '/odds',
  path: '/odds',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmakersRoute = BookmakersRouteImport.update({
  id: '/bookmakers',
  path: '/bookmakers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bookmakers': typeof BookmakersRoute
  '/live': typeof LiveRoute
  '/odds': typeof OddsRoute
  '/opportunities': typeof OpportunitiesRoute
  '/quick': typeof QuickRoute
  '/ru-live': typeof RuLiveRoute
  '/scanner': typeof ScannerRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bookmakers': typeof BookmakersRoute
  '/live': typeof LiveRoute
  '/odds': typeof OddsRoute
  '/opportunities': typeof OpportunitiesRoute
  '/quick': typeof QuickRoute
  '/ru-live': typeof RuLiveRoute
  '/scanner': typeof ScannerRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bookmakers': typeof BookmakersRoute
  '/live': typeof LiveRoute
  '/odds': typeof OddsRoute
  '/opportunities': typeof OpportunitiesRoute
  '/quick': typeof QuickRoute
  '/ru-live': typeof RuLiveRoute
  '/scanner': typeof ScannerRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bookmakers'
    | '/live'
    | '/odds'
    | '/opportunities'
    | '/quick'
    | '/ru-live'
    | '/scanner'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bookmakers'
    | '/live'
    | '/odds'
    | '/opportunities'
    | '/quick'
    | '/ru-live'
    | '/scanner'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/bookmakers'
    | '/live'
    | '/odds'
    | '/opportunities'
    | '/quick'
    | '/ru-live'
    | '/scanner'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookmakersRoute: typeof BookmakersRoute
  LiveRoute: typeof LiveRoute
  OddsRoute: typeof OddsRoute
  OpportunitiesRoute: typeof OpportunitiesRoute
  QuickRoute: typeof QuickRoute
  RuLiveRoute: typeof RuLiveRoute
  ScannerRoute: typeof ScannerRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru-live': {
      id: '/ru-live'
      path: '/ru-live'
      fullPath: '/ru-live'
      preLoaderRoute: typeof RuLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quick': {
      id: '/quick'
      path: '/quick'
      fullPath: '/quick'
      preLoaderRoute: typeof QuickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/odds': {
      id: '/odds'
      path: '/odds'
      fullPath: '/odds'
      preLoaderRoute: typeof OddsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmakers': {
      id: '/bookmakers'
      path: '/bookmakers'
      fullPath: '/bookmakers'
      preLoaderRoute: typeof BookmakersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookmakersRoute: BookmakersRoute,
  LiveRoute: LiveRoute,
  OddsRoute: OddsRoute,
  OpportunitiesRoute: OpportunitiesRoute,
  QuickRoute: QuickRoute,
  RuLiveRoute: RuLiveRoute,
  ScannerRoute: ScannerRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
