/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SurebetsRouteImport } from './routes/surebets'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScannerRouteImport } from './routes/scanner'
import { Route as RuLiveRouteImport } from './routes/ru-live'
import { Route as QuickRouteImport } from './routes/quick'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as OddsRouteImport } from './routes/odds'
import { Route as BookmakersRouteImport } from './routes/bookmakers'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiV1SurebetsRouteImport } from './routes/api/v1/surebets'
import { Route as ApiPublicScanRuLatestRouteImport } from './routes/api/public/scan-ru-latest'
import { Route as ApiPublicScanRuRouteImport } from './routes/api/public/scan-ru'
import { Route as ApiPublicScanRouteImport } from './routes/api/public/scan'

const SurebetsRoute = SurebetsRouteImport.update({
  id: '/surebets',
  path: '/surebets',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const RuLiveRoute = RuLiveRouteImport.update({
  id: '/ru-live',
  path: '/ru-live',
  getParentRoute: () => rootRouteImport,
} as any)
const QuickRoute = QuickRouteImport.update({
  id: '/quick',
  path: '/quick',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const OddsRoute = OddsRouteImport.update({
  id: '/odds',
  path: '/odds',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmakersRoute = BookmakersRouteImport.update({
  id: '/bookmakers',
  path: '/bookmakers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SurebetsRoute = ApiV1SurebetsRouteImport.update({
  id: '/api/v1/surebets',
  path: '/api/v1/surebets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicScanRuLatestRoute = ApiPublicScanRuLatestRouteImport.update({
  id: '/api/public/scan-ru-latest',
  path: '/api/public/scan-ru-latest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicScanRuRoute = ApiPublicScanRuRouteImport.update({
  id: '/api/public/scan-ru',
  path: '/api/public/scan-ru',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicScanRoute = ApiPublicScanRouteImport.update({
  id: '/api/public/scan',
  path: '/api/public/scan',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bookmakers': typeof BookmakersRoute
  '/odds': typeof OddsRoute
  '/opportunities': typeof OpportunitiesRoute
  '/quick': typeof QuickRoute
  '/ru-live': typeof RuLiveRoute
  '/scanner': typeof ScannerRoute
  '/settings': typeof SettingsRoute
  '/surebets': typeof SurebetsRoute
  '/api/public/scan': typeof ApiPublicScanRoute
  '/api/public/scan-ru': typeof ApiPublicScanRuRoute
  '/api/public/scan-ru-latest': typeof ApiPublicScanRuLatestRoute
  '/api/v1/surebets': typeof ApiV1SurebetsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bookmakers': typeof BookmakersRoute
  '/odds': typeof OddsRoute
  '/opportunities': typeof OpportunitiesRoute
  '/quick': typeof QuickRoute
  '/ru-live': typeof RuLiveRoute
  '/scanner': typeof ScannerRoute
  '/settings': typeof SettingsRoute
  '/surebets': typeof SurebetsRoute
  '/api/public/scan': typeof ApiPublicScanRoute
  '/api/public/scan-ru': typeof ApiPublicScanRuRoute
  '/api/public/scan-ru-latest': typeof ApiPublicScanRuLatestRoute
  '/api/v1/surebets': typeof ApiV1SurebetsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bookmakers': typeof BookmakersRoute
  '/odds': typeof OddsRoute
  '/opportunities': typeof OpportunitiesRoute
  '/quick': typeof QuickRoute
  '/ru-live': typeof RuLiveRoute
  '/scanner': typeof ScannerRoute
  '/settings': typeof SettingsRoute
  '/surebets': typeof SurebetsRoute
  '/api/public/scan': typeof ApiPublicScanRoute
  '/api/public/scan-ru': typeof ApiPublicScanRuRoute
  '/api/public/scan-ru-latest': typeof ApiPublicScanRuLatestRoute
  '/api/v1/surebets': typeof ApiV1SurebetsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bookmakers'
    | '/odds'
    | '/opportunities'
    | '/quick'
    | '/ru-live'
    | '/scanner'
    | '/settings'
    | '/surebets'
    | '/api/public/scan'
    | '/api/public/scan-ru'
    | '/api/public/scan-ru-latest'
    | '/api/v1/surebets'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bookmakers'
    | '/odds'
    | '/opportunities'
    | '/quick'
    | '/ru-live'
    | '/scanner'
    | '/settings'
    | '/surebets'
    | '/api/public/scan'
    | '/api/public/scan-ru'
    | '/api/public/scan-ru-latest'
    | '/api/v1/surebets'
  id:
    | '__root__'
    | '/'
    | '/bookmakers'
    | '/odds'
    | '/opportunities'
    | '/quick'
    | '/ru-live'
    | '/scanner'
    | '/settings'
    | '/surebets'
    | '/api/public/scan'
    | '/api/public/scan-ru'
    | '/api/public/scan-ru-latest'
    | '/api/v1/surebets'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookmakersRoute: typeof BookmakersRoute
  OddsRoute: typeof OddsRoute
  OpportunitiesRoute: typeof OpportunitiesRoute
  QuickRoute: typeof QuickRoute
  RuLiveRoute: typeof RuLiveRoute
  ScannerRoute: typeof ScannerRoute
  SettingsRoute: typeof SettingsRoute
  SurebetsRoute: typeof SurebetsRoute
  ApiPublicScanRoute: typeof ApiPublicScanRoute
  ApiPublicScanRuRoute: typeof ApiPublicScanRuRoute
  ApiPublicScanRuLatestRoute: typeof ApiPublicScanRuLatestRoute
  ApiV1SurebetsRoute: typeof ApiV1SurebetsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/surebets': {
      id: '/surebets'
      path: '/surebets'
      fullPath: '/surebets'
      preLoaderRoute: typeof SurebetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru-live': {
      id: '/ru-live'
      path: '/ru-live'
      fullPath: '/ru-live'
      preLoaderRoute: typeof RuLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quick': {
      id: '/quick'
      path: '/quick'
      fullPath: '/quick'
      preLoaderRoute: typeof QuickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/odds': {
      id: '/odds'
      path: '/odds'
      fullPath: '/odds'
      preLoaderRoute: typeof OddsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmakers': {
      id: '/bookmakers'
      path: '/bookmakers'
      fullPath: '/bookmakers'
      preLoaderRoute: typeof BookmakersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/surebets': {
      id: '/api/v1/surebets'
      path: '/api/v1/surebets'
      fullPath: '/api/v1/surebets'
      preLoaderRoute: typeof ApiV1SurebetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/scan-ru-latest': {
      id: '/api/public/scan-ru-latest'
      path: '/api/public/scan-ru-latest'
      fullPath: '/api/public/scan-ru-latest'
      preLoaderRoute: typeof ApiPublicScanRuLatestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/scan-ru': {
      id: '/api/public/scan-ru'
      path: '/api/public/scan-ru'
      fullPath: '/api/public/scan-ru'
      preLoaderRoute: typeof ApiPublicScanRuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/scan': {
      id: '/api/public/scan'
      path: '/api/public/scan'
      fullPath: '/api/public/scan'
      preLoaderRoute: typeof ApiPublicScanRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookmakersRoute: BookmakersRoute,
  OddsRoute: OddsRoute,
  OpportunitiesRoute: OpportunitiesRoute,
  QuickRoute: QuickRoute,
  RuLiveRoute: RuLiveRoute,
  ScannerRoute: ScannerRoute,
  SettingsRoute: SettingsRoute,
  SurebetsRoute: SurebetsRoute,
  ApiPublicScanRoute: ApiPublicScanRoute,
  ApiPublicScanRuRoute: ApiPublicScanRuRoute,
  ApiPublicScanRuLatestRoute: ApiPublicScanRuLatestRoute,
  ApiV1SurebetsRoute: ApiV1SurebetsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
